# Generated by Django 6.0.4 on 2026-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_seed_fraud_thresholds'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accessevent',
            new_name='access_cont_marina__7ad651_idx',
            old_name='ac_event_marina_occurred_idx',
        ),
        migrations.RenameIndex(
            model_name='accessevent',
            new_name='access_cont_marina__1b277f_idx',
            old_name='ac_event_marina_member_idx',
        ),
        migrations.RenameIndex(
            model_name='accessevent',
            new_name='access_cont_marina__0c88df_idx',
            old_name='ac_event_marina_reader_idx',
        ),
        migrations.RenameIndex(
            model_name='anprevent',
            new_name='access_cont_marina__a497e6_idx',
            old_name='anpr_event_marina_occurred_idx',
        ),
        migrations.RenameIndex(
            model_name='anprevent',
            new_name='access_cont_marina__e7eaf9_idx',
            old_name='anpr_event_plate_idx',
        ),
        migrations.AlterField(
            model_name='zoneaccessrule',
            name='allowed_piers',
            field=models.JSONField(blank=True, default=list, help_text="Explicit pier label allow-list when link_to_berth_pier=True and you want to restrict to a subset of piers regardless of the member's berth assignment. Empty list = all piers permitted (berth assignment is the only gate)."),
        ),
    ]
