# Generated by Django 6.0.4 on 2026-04-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('berths', '0001_initial'),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('transient', 'Transient'), ('seasonal', 'Seasonal')], default='transient', max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.IntegerField(default=1)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='berths.berth')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.marina')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
