# Generated by Django 6.0.4 on 2026-04-28 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('berths', '0001_initial'),
        ('members', '0001_initial'),
        ('reservations', '0002_booking_status_choices'),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('guest_phone', models.CharField(blank=True, max_length=50)),
                ('guest_email', models.CharField(blank=True, max_length=200)),
                ('guest_vessel', models.CharField(blank=True, max_length=200)),
                ('guest_loa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('booking_type', models.CharField(choices=[('transient', 'Transient'), ('seasonal', 'Seasonal')], default='transient', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='berths.berth')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='reservations.booking')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='accounts.marina')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='members.member')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='vessels.vessel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
