# Generated by Django 6.0.4 on 2026-04-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0001_initial'),
        ('reservations', '0003_add_bookingrequest'),
        ('vessels', '0004_alter_vessel_options_alter_vesselcertificate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='boat_beam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='boat_loa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='berth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='berths.berth'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('awaiting_payment', 'Awaiting Payment'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('pending', 'Pending'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('overstay', 'Overstay')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vessels.vessel'),
        ),
    ]
