# Generated by Django 6.0.4 on 2026-04-30 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_booking_boat_beam_booking_boat_loa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stripe_session_id',
        ),
    ]
