# Generated by Django 6.0.4 on 2026-05-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_booking_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='boat_draft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_doc',
            field=models.FileField(blank=True, null=True, upload_to='insurance/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pre_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='self_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='self_checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='waiver_envelope_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='waiver_signed',
            field=models.BooleanField(default=False),
        ),
    ]
