# Generated by Django 6.0.4 on 2026-05-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_booking_portal_checkin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('awaiting_payment', 'Awaiting Payment'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('pending', 'Pending'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('overstay', 'Overstay'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
