# Generated by Django 6.0.4 on 2026-05-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_booking_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('direct', 'Direct'), ('mysea', 'mySea')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='mysea_event_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
