# Generated by Django 6.0.4 on 2026-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_booking_source_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(blank=True, default='direct', max_length=100),
        ),
    ]
