# Generated by Django 6.0.4 on 2026-05-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_booking_dates_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_dates_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='eta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
