# Generated by Django 6.0.4 on 2026-05-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_booking_track2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dynamic_price_applied',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_hourly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='ota_commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='OTA commission amount retained by the channel.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
