# Generated by Django 6.0.4 on 2026-05-12 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_vat_number_to_marina_group'),
        ('berths', '0032_berthcategory_tagline_highlights'),
        ('members', '0006_member_is_archived_member_merged_into_and_more'),
        ('reservations', '0014_booking_no_show_status'),
        ('vessels', '0004_alter_vessel_options_alter_vesselcertificate_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('awaiting_payment', 'Awaiting Payment'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('pending', 'Pending'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('overstay', 'Overstay'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('waiver_envelope_id', models.CharField(blank=True, max_length=255, null=True)),
                ('waiver_signed', models.BooleanField(default=False)),
                ('self_checked_in', models.BooleanField(default=False)),
                ('self_checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('booking_source', models.CharField(blank=True, default='direct', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legacy_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='reservations.booking')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.marina')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(blank=True, max_length=200)),
                ('booking_type', models.CharField(choices=[('transient', 'Transient'), ('seasonal', 'Seasonal')], default='transient', max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.IntegerField(default=1)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('boat_loa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boat_beam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('boat_draft', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eta', models.TimeField(blank=True, null=True)),
                ('is_sublet', models.BooleanField(default=False)),
                ('is_hourly', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('dynamic_price_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ota_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mysea_event_uid', models.CharField(blank=True, default='', max_length=255)),
                ('insurance_doc', models.FileField(blank=True, null=True, upload_to='insurance/')),
                ('pre_cleared', models.BooleanField(default=False)),
                ('insurance_verified', models.BooleanField(default=False)),
                ('registration_verified', models.BooleanField(default=False)),
                ('waiver_verified', models.BooleanField(default=False)),
                ('document_gate_cleared', models.BooleanField(default=False)),
                ('document_gate_cleared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('berth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_items', to='berths.berth')),
                ('document_gate_cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_item_gate_clearances', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.reservation')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_items', to='vessels.vessel')),
            ],
            options={
                'ordering': ['check_in'],
            },
        ),
    ]
