# Generated by Django 6.0.4 on 2026-05-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_backfill_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('confirmed', 'Confirmed'), ('released', 'Released')], default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('awaiting_payment', 'Awaiting Payment'), ('pending_payment', 'Pending Payment'), ('pending_checkout', 'Pending Checkout'), ('confirmed', 'Confirmed'), ('pending', 'Pending'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('overstay', 'Overstay'), ('no_show', 'No Show'), ('cancelled', 'Cancelled'), ('abandoned', 'Abandoned')], default='pending', max_length=20),
        ),
    ]
