# Generated by Django 6.0.4 on 2026-05-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_reservation_checkout_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('awaiting_payment', 'Awaiting Payment'), ('pending_payment', 'Pending Payment'), ('pending_checkout', 'Pending Checkout'), ('confirmed', 'Confirmed'), ('pending', 'Pending'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('overstay', 'Overstay'), ('no_show', 'No Show'), ('cancelled', 'Cancelled'), ('abandoned', 'Abandoned'), ('pending_review', 'Pending Manager Review')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationitem',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('confirmed', 'Confirmed'), ('released', 'Released'), ('unassigned', 'Unassigned')], default='confirmed', max_length=20),
        ),
    ]
