# Generated by Django 6.0.5 on 2026-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_reservation_pending_review_unassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ais_no_show_predicted',
            field=models.BooleanField(default=False, help_text='Set True by AIS Phase 2 when a booking has no AIS contact within 1 h of expected arrival.'),
        ),
    ]
