# Generated by Django 6.0.5 on 2026-05-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_booking_ais_no_show_predicted'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tax_exempt_override',
            field=models.BooleanField(default=False, help_text='When True, all invoice lines generated for this booking are zero-tax, overriding the member-level setting and the chargeable item tax category.'),
        ),
    ]
