# Generated by Django 6.0.4 on 2026-05-08 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_marinagroup_marina_harbour_master_email_and_more'),
        ('housekeeping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('vessel', 'Charter Vessel'), ('accommodation', 'Accommodation Unit'), ('facility', 'Facility / Common Area')], max_length=20)),
                ('unit_label', models.CharField(max_length=200)),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('next_run_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_schedules', to='accounts.marina')),
            ],
            options={
                'ordering': ['unit_label'],
            },
        ),
    ]
