# Generated by Django 6.0.4 on 2026-05-08 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_marinagroup_marina_harbour_master_email_and_more'),
        ('berths', '0030_berth_intelligence_models'),
        ('members', '0006_member_is_archived_member_merged_into_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerthListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_party', models.CharField(choices=[('member', 'Berth Holder'), ('marina', 'Marina')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('under_offer', 'Under Offer'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('show_asking_price', models.BooleanField(default=False)),
                ('licence_transfer_terms', models.TextField(blank=True)),
                ('length_m', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('max_beam_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_draft_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_power', models.BooleanField(default=False)),
                ('has_water', models.BooleanField(default=False)),
                ('publish_to_portal', models.BooleanField(default=True)),
                ('publish_to_network', models.BooleanField(default=False)),
                ('publish_to_third_party', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_berth_listings', to='berths.berth')),
                ('listed_by_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_listed_berths', to='members.member')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='accounts.marina')),
                ('sold_to_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_purchased_berths', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BerthEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquirer_name', models.CharField(blank=True, max_length=200)),
                ('enquirer_email', models.EmailField(blank=True, max_length=254)),
                ('enquirer_phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquirer_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_berth_enquiries', to='members.member')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_berth_enquiries', to='accounts.marina')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='marketplace.berthlisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BerthListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='berth_listing_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='marketplace.berthlisting')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listing_photos', to='accounts.marina')),
            ],
            options={
                'ordering': ['sort_order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('matched', 'Matched'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], default='available', max_length=20)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('desired_location', models.CharField(blank=True, max_length=500)),
                ('network_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_listings', to='berths.berth')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_listings', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_listings', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Signature'), ('agreed', 'Agreed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('party_a_start_date', models.DateField()),
                ('party_a_end_date', models.DateField()),
                ('party_b_start_date', models.DateField()),
                ('party_b_end_date', models.DateField()),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='exchange_agreements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_agreements', to='accounts.marina')),
                ('listing_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_a', to='marketplace.exchangelisting')),
                ('listing_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_b', to='marketplace.exchangelisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
