# Generated by Django 6.0.4 on 2026-04-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaulOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haul_type', models.CharField(choices=[('haul_out', 'Haul Out'), ('splash', 'Splash')], default='haul_out', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('equipment', models.CharField(blank=True, max_length=200)),
                ('crew', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haul_outs', to='accounts.marina')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('part_no', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('par', models.IntegerField(default=0, help_text='Minimum stock level')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='accounts.marina')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending_auth', 'Pending Auth'), ('authorised', 'Authorised'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending_auth', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='accounts.marina')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('checked_out', 'Checked Out'), ('service_due', 'Service Due')], default='available', max_length=20)),
                ('checked_out_to', models.CharField(blank=True, max_length=200)),
                ('calibration_due', models.DateField(blank=True, null=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='accounts.marina')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boatyard.workorder')),
            ],
        ),
    ]
