# Generated by Django 4.2.29 on 2026-04-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0004_alter_vessel_options_alter_vesselcertificate_options'),
        ('accounts', '0002_marina_operations_paused'),
        ('boatyard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haulout',
            options={'ordering': ['-scheduled_at']},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='haulout',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tool',
            name='serial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.CreateModel(
            name='StorageSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(max_length=50)),
                ('col', models.CharField(max_length=10)),
                ('tier', models.IntegerField(default=1)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_slots', to='accounts.marina')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_slot', to='vessels.vessel')),
            ],
            options={
                'ordering': ['lane', 'col', 'tier'],
                'unique_together': {('marina', 'lane', 'col', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='LaunchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(blank=True, max_length=200)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('launching', 'Launching'), ('retrieved', 'Retrieved')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_requests', to='accounts.marina')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch_requests', to='boatyard.storageslot')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='launch_requests', to='vessels.vessel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trade', models.CharField(blank=True, max_length=200)),
                ('working_on', models.CharField(blank=True, max_length=200)),
                ('access_start', models.DateField()),
                ('access_end', models.DateField(blank=True, null=True)),
                ('vessel_owner', models.CharField(blank=True, max_length=200)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='accounts.marina')),
            ],
            options={
                'ordering': ['access_start'],
            },
        ),
    ]
