# Generated by Django 6.0.4 on 2026-05-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_marinagroup_marina_harbour_master_email_and_more'),
        ('billing', '0015_chargeableitem_is_upsell_eligible_invoice_tenant'),
        ('boatyard', '0003_track6_drystack_concierge'),
        ('vessels', '0004_alter_vessel_options_alter_vesselcertificate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(blank=True, max_length=200)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_posts', to='accounts.marina')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('hull_number', models.CharField(blank=True, max_length=100)),
                ('vessel_type', models.CharField(blank=True, max_length=200)),
                ('loa_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_build', 'In Build'), ('sea_trials', 'Sea Trials'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planning', max_length=20)),
                ('keel_laid_date', models.DateField(blank=True, null=True)),
                ('launch_target_date', models.DateField(blank=True, null=True)),
                ('actual_launch_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_projects', to='accounts.marina')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_project', to='vessels.vessel')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='build_project', to='boatyard.workorder')),
            ],
            options={
                'ordering': ['-keel_laid_date'],
            },
        ),
        migrations.CreateModel(
            name='BuildMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_due_days', models.IntegerField(default=14)),
                ('sort_order', models.IntegerField(default=0)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_milestone', to='billing.invoice')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_milestones', to='accounts.marina')),
                ('build_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='boatyard.buildproject')),
            ],
            options={
                'ordering': ['sort_order', 'planned_date'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('unit_cost_at_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('procurement_status', models.CharField(choices=[('not_ordered', 'Not Ordered'), ('ordered', 'Ordered'), ('received', 'Received'), ('consumed', 'Consumed')], default='not_ordered', max_length=20)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='accounts.marina')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boatyard.part')),
                ('build_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='boatyard.buildproject')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_templates', to='accounts.marina')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobTemplatePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boatyard.part')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='boatyard.jobtemplate')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='JobTemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.IntegerField(default=1)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boatyard.jobtemplate')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('warehouse', 'Main Warehouse'), ('truck', 'Service Truck')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.marina')),
            ],
            options={
                'ordering': ['location_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('par', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='accounts.marina')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='boatyard.part')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_levels', to='boatyard.location')),
            ],
            options={
                'ordering': ['location', 'part'],
                'unique_together': {('part', 'location')},
            },
        ),
        migrations.CreateModel(
            name='ServiceTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(blank=True, max_length=50)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='truck', to='boatyard.location')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_trucks', to='accounts.marina')),
            ],
            options={
                'ordering': ['location__name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('import_format', models.CharField(choices=[('csv', 'CSV'), ('edi', 'EDI'), ('api', 'API Feed')], max_length=10)),
                ('file_url', models.URLField(blank=True)),
                ('api_endpoint', models.URLField(blank=True)),
                ('flag_threshold_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('status', models.CharField(choices=[('pending_mapping', 'Pending Column Mapping'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending_mapping', max_length=20)),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_updated', models.IntegerField(default=0)),
                ('rows_flagged', models.IntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('imported_by', models.CharField(blank=True, max_length=200)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_files', to='accounts.marina')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='PartPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('new_unit_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_price_history', to='accounts.marina')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='boatyard.part')),
                ('price_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to='boatyard.supplierpricefile')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TruckStockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('to_truck', 'Warehouse → Truck'), ('from_truck', 'Truck → Warehouse')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('transferred_by', models.CharField(blank=True, max_length=200)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_transfers', to='accounts.marina')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_transfers', to='boatyard.part')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='boatyard.servicetruck')),
            ],
            options={
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open — Cycle Count Required'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolved_by', models.CharField(blank=True, max_length=200)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_anomalies', to='accounts.marina')),
                ('inventory_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='boatyard.inventorylevel')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='boatyard.truckstocktransfer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('covers_parts', models.BooleanField(default=True)),
                ('covers_labour', models.BooleanField(default=False)),
                ('labour_rate_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reimbursement_rate_pct', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('avg_processing_days', models.IntegerField(blank=True, null=True)),
                ('submission_instructions', models.TextField(blank=True)),
                ('pdf_template_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_agreements', to='accounts.marina')),
            ],
            options={
                'ordering': ['manufacturer_name'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_reference', models.CharField(blank=True, max_length=100)),
                ('parts_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_reimbursed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('approved', 'Approved'), ('reimbursed', 'Reimbursed'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reimbursed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_document_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='boatyard.warrantyagreement')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claims', to='accounts.marina')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='boatyard.workorder')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('planned_start', models.DateField()),
                ('planned_end', models.DateField()),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('baseline_start', models.DateField(blank=True, null=True)),
                ('baseline_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('percent_complete', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wo_tasks', to='accounts.marina')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boatyard.workorder')),
            ],
            options={
                'ordering': ['sort_order', 'planned_start'],
            },
        ),
        migrations.CreateModel(
            name='BatchJobPostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='boatyard.batchjobpost')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_lines', to='boatyard.workorder')),
                ('work_order_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_lines', to='boatyard.workordertask')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierColumnMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('mapping', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_column_maps', to='accounts.marina')),
            ],
            options={
                'unique_together': {('marina', 'supplier_name')},
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('fs', 'Finish-to-Start'), ('ss', 'Start-to-Start'), ('ff', 'Finish-to-Finish'), ('sf', 'Start-to-Finish')], default='fs', max_length=2)),
                ('lag_days', models.IntegerField(default=0)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_dependencies', to='accounts.marina')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='boatyard.workordertask')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='boatyard.workordertask')),
            ],
            options={
                'unique_together': {('predecessor', 'successor')},
            },
        ),
    ]
