# Generated by Django 6.0.4 on 2026-05-08 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('boatyard', '0004_batchjobpost_buildproject_buildmilestone_bomitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyclaim',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claim', to='accounting.journalentry'),
        ),
    ]
