# Generated by Django 6.0.4 on 2026-05-08 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_marinagroup_marina_harbour_master_email_and_more'),
        ('boatyard', '0005_warrantyclaim_journal_entry'),
        ('vessels', '0004_alter_vessel_options_alter_vesselcertificate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift_type', models.CharField(choices=[('haul_out', 'Haul-out'), ('splash', 'Splash / Launch'), ('travel_lift', 'Travel Lift Transfer'), ('crane', 'Crane Lift')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.CharField(blank=True, max_length=200)),
                ('operator', models.CharField(blank=True, max_length=200)),
                ('boat_weight_t', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lift_operations', to='accounts.marina')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lift_operations', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='PaintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint_type', models.CharField(choices=[('antifoul', 'Antifoul'), ('topside', 'Topside'), ('primer', 'Primer'), ('gelcoat', 'Gelcoat'), ('varnish', 'Varnish'), ('other', 'Other')], max_length=20)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('colour', models.CharField(blank=True, max_length=100)),
                ('applied_date', models.DateField()),
                ('applied_by', models.CharField(blank=True, max_length=200)),
                ('coats', models.PositiveIntegerField(default=1)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paint_records', to='accounts.marina')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_records', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='PartsInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_inventory', to='accounts.marina')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bay_type', models.CharField(choices=[('general', 'General'), ('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('paint', 'Paint / Spray'), ('welding', 'Welding'), ('rigging', 'Rigging')], default='general', max_length=20)),
                ('capacity', models.DecimalField(blank=True, decimal_places=1, help_text='Max LOA in metres', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bays', to='accounts.marina')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('trade', models.CharField(blank=True, help_text='e.g. Marine Electrical, Rigging', max_length=200)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractors', to='accounts.marina')),
            ],
            options={
                'ordering': ['company'],
            },
        ),
    ]
