# Generated by Django 6.0.5 on 2026-05-16 10:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_add_sage_business_cloud_platform'),
        ('accounts', '0033_backfill_email_verified_at'),
        ('billing', '0021_invoice_reservation_backfill'),
        ('staff', '0003_staffmember_is_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('generic_csv', 'Generic CSV'), ('qbo_csv', 'QuickBooks Online CSV'), ('xero_csv', 'Xero CSV'), ('tax_summary_csv', 'Tax Summary CSV')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category_filter', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/')),
                ('row_count', models.IntegerField(default=0)),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='accounts.marina')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to='staff.staffmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payout_id', models.CharField(max_length=200)),
                ('stripe_account_id', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('created_at_stripe', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('in_transit', 'In Transit'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('bank_account_last4', models.CharField(blank=True, max_length=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('reconciled', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout', to='accounting.journalentry')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounts.marina')),
            ],
            options={
                'ordering': ['-arrival_date', '-synced_at'],
                'unique_together': {('marina', 'stripe_payout_id')},
            },
        ),
        migrations.CreateModel(
            name='PayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('dispute', 'Dispute / Chargeback'), ('adjustment', 'Adjustment'), ('fee', 'Fee'), ('other', 'Other')], default='charge', max_length=20)),
                ('stripe_balance_txn_id', models.CharField(blank=True, max_length=200)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=200)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at_stripe', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_lines', to='billing.invoice')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.payout')),
            ],
            options={
                'ordering': ['payout', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GLCodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeable_category', models.CharField(max_length=30)),
                ('external_gl_code', models.CharField(blank=True, max_length=50)),
                ('external_gl_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_code_mappings', to='accounting.costcentre')),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_code_mappings', to='accounting.account')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_code_mappings', to='accounts.marina')),
            ],
            options={
                'ordering': ['chargeable_category'],
                'unique_together': {('marina', 'chargeable_category')},
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('jurisdiction_country', models.CharField(blank=True, max_length=2)),
                ('jurisdiction_state', models.CharField(blank=True, max_length=100)),
                ('jurisdiction_county', models.CharField(blank=True, max_length=100)),
                ('jurisdiction_city', models.CharField(blank=True, max_length=100)),
                ('reportable_category', models.CharField(choices=[('sales_tax', 'Sales Tax'), ('transient_tax', 'Transient / Hotel Tax'), ('tourism_levy', 'Tourism Levy'), ('fuel_excise', 'Fuel Excise'), ('vat_standard', 'VAT Standard'), ('vat_reduced', 'VAT Reduced'), ('vat_zero', 'VAT Zero'), ('vat_exempt', 'VAT Exempt'), ('gst', 'GST'), ('pst', 'PST'), ('hst', 'HST'), ('none', 'No Tax / Exempt')], default='sales_tax', max_length=30)),
                ('external_qbo_code', models.CharField(blank=True, max_length=100)),
                ('external_xero_code', models.CharField(blank=True, max_length=100)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_codes', to='accounts.marina')),
                ('tax_rate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_code', to='billing.taxrate')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('marina', 'name')},
            },
        ),
    ]
