# Generated by Django 6.0.5 on 2026-05-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('booking_request', 'Booking Request'), ('overdue_invoice', 'Overdue Invoice'), ('maintenance_assigned', 'Maintenance Assigned'), ('activity_request', 'Activity Request')], max_length=30),
        ),
    ]
