# Generated by Django 6.0.5 on 2026-05-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_activity_request_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('booking_request', 'Booking Request'), ('overdue_invoice', 'Overdue Invoice'), ('maintenance_assigned', 'Maintenance Assigned'), ('activity_request', 'Activity Request'), ('ais_auto_checkin', 'AIS Auto Check-in'), ('ais_auto_checkout', 'AIS Auto Check-out'), ('ais_no_show_predicted', 'AIS No-Show Predicted')], max_length=30),
        ),
    ]
