# Generated by Django 6.0.4 on 2026-05-08 08:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_remove_marina_channel_fields'),
        ('berths', '0027_logical_pier'),
        ('members', '0004_member_boater_user'),
        ('reservations', '0011_remove_booking_booking_dates_idx_booking_eta_and_more'),
        ('vessels', '0004_alter_vessel_options_alter_vesselcertificate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_from', models.DateField()),
                ('desired_to', models.DateField(blank=True, null=True)),
                ('booking_type', models.CharField(choices=[('transient', 'Transient'), ('seasonal', 'Seasonal')], default='seasonal', max_length=20)),
                ('vessel_loa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vessel_beam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vessel_draft', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('priority_score', models.IntegerField(default=0, help_text='Computed score: higher = gets offered first when a berth frees up.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_source', to='reservations.booking')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='members.member')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-priority_score', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='YieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('occupancy_threshold', 'Occupancy Threshold'), ('seasonal', 'Seasonal Date Range'), ('last_minute', 'Last-Minute Discount'), ('length_of_stay', 'Length-of-Stay Discount'), ('early_bird', 'Early Bird')], max_length=30)),
                ('parameters', models.JSONField(default=dict)),
                ('multiplier', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='e.g. 1.20 = 20% surcharge, 0.85 = 15% discount', max_digits=5)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first. Only the first matching rule applies.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_rules', to='accounts.marina')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='YieldApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yield_application', to='reservations.booking')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_applications', to='accounts.marina')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='revenue.yieldrule')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('peak', 'Peak'), ('shoulder', 'Shoulder'), ('off', 'Off-Season')], max_length=20)),
                ('booking_type', models.CharField(choices=[('transient', 'Transient'), ('seasonal', 'Seasonal')], default='transient', max_length=20)),
                ('base_nightly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_stay_nights', models.IntegerField(default=1)),
                ('berth_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tiers', to='berths.berthcategory')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tiers', to='accounts.marina')),
            ],
            options={
                'ordering': ['berth_category', 'season'],
                'unique_together': {('marina', 'berth_category', 'season', 'booking_type')},
            },
        ),
    ]
