# Generated by Django 6.0.4 on 2026-04-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initials', models.CharField(blank=True, max_length=5)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('contract', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('seasonal', 'Seasonal'), ('contractor', 'Contractor')], default='full_time', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='accounts.marina')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('day', models.CharField(choices=[('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], max_length=3)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_off', models.BooleanField(default=False)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='accounts.marina')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_body', models.CharField(blank=True, max_length=200)),
                ('issued', models.DateField(blank=True, null=True)),
                ('expires', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('due_soon', 'Due Soon'), ('expired', 'Expired')], default='valid', max_length=20)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='accounts.marina')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='staff.staffmember')),
            ],
        ),
    ]
