# Generated by Django 6.0.4 on 2026-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_certification_pdf_file_staffmember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='is_contractor',
            field=models.BooleanField(default=False, help_text='Contractor skippers appear in charter assignments but are excluded from payroll views.'),
        ),
    ]
