# Generated by Django 6.0.4 on 2026-05-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='impersonation_session_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='impersonator_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
