# Generated by Django 6.0.5 on 2026-05-17 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_marina_billing_admin_override_and_more'),
        ('admin_portal', '0002_auditlog_impersonation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedStripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingStateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=100)),
                ('stripe_event_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_state_changes', to='accounts.marina')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['marina', '-created_at'], name='admin_porta_marina__e6a8fc_idx')],
            },
        ),
    ]
