# Generated by Django 6.0.5 on 2026-05-16 10:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0034_marina_max_waitlist_declines'),
        ('berths', '0032_berthcategory_tagline_highlights'),
        ('members', '0006_member_is_archived_member_merged_into_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(blank=True, max_length=30)),
                ('vessel_type', models.CharField(blank=True, max_length=40)),
                ('vessel_loa_m', models.DecimalField(decimal_places=1, max_digits=6)),
                ('vessel_beam_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vessel_draft_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pref_min_loa_m', models.DecimalField(decimal_places=1, max_digits=6)),
                ('pref_max_loa_m', models.DecimalField(decimal_places=1, max_digits=6)),
                ('priority_score', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('deposit_amount_cents', models.IntegerField(default=0)),
                ('deposit_state', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('manual_refund_required', 'Manual Refund Required'), ('applied_to_lease', 'Applied to Lease')], default='unpaid', max_length=30)),
                ('deposit_payment_intent_id', models.CharField(blank=True, max_length=120)),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('decline_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('converted', 'Converted'), ('withdrawn', 'Withdrawn'), ('removed_max_declines', 'Removed - Max Declines'), ('expired', 'Expired')], default='pending', max_length=30)),
                ('applied_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasonal_waitlist_entries', to='members.member')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_waitlist_entries', to='accounts.marina')),
                ('pref_pier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='berths.pier')),
            ],
            options={
                'ordering': ['priority_score', 'applied_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RefundAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('audit_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_actions', to='waitlist.waitlistentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magic_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('offered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=400)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='waitlist.waitlistentry')),
                ('offered_berth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasonal_waitlist_offers', to='berths.berth')),
            ],
            options={
                'ordering': ['-offered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['marina', 'status', 'priority_score'], name='waitlist_wa_marina__cc63c3_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['marina', 'applicant_email'], name='waitlist_wa_marina__3a13fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='waitlistoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('outcome', 'pending')), fields=('entry',), name='waitlist_one_open_offer_per_entry'),
        ),
        migrations.AddConstraint(
            model_name='waitlistoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('outcome', 'pending')), fields=('offered_berth',), name='waitlist_one_open_offer_per_berth'),
        ),
    ]
