# Generated by Django 6.0.4 on 2026-04-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('event_type', models.CharField(choices=[('race', 'Race'), ('rally', 'Rally'), ('social', 'Social'), ('corporate', 'Corporate'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('organiser', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('attendance', models.IntegerField(default=0)),
                ('fleet_count', models.IntegerField(default=0)),
                ('berths_blocked', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.marina')),
            ],
        ),
        migrations.CreateModel(
            name='VenueHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity_seated', models.IntegerField(default=0)),
                ('capacity_standing', models.IntegerField(default=0)),
                ('facilities', models.JSONField(blank=True, default=list)),
                ('day_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_hires', to='accounts.marina')),
            ],
        ),
    ]
