# Generated by Django 6.0.5 on 2026-05-15 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_marina_require_mfa'),
        ('security', '0001_initial_mfa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarinaIPAllowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(max_length=43)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_allowlist', to='accounts.marina')),
            ],
            options={
                'unique_together': {('marina', 'cidr')},
            },
        ),
    ]
