# Generated by Django 6.0.5 on 2026-05-15 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_backfill_email_verified_at'),
        ('security', '0002_marinaipallowlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('mfa_enrolled', 'MFA enrolled'), ('mfa_disabled', 'MFA disabled'), ('mfa_failed', 'MFA verification failed'), ('mfa_succeeded', 'MFA verification succeeded'), ('backup_code_used', 'Backup code used'), ('ip_allowlist_added', 'IP allowlist entry added'), ('ip_allowlist_removed', 'IP allowlist entry removed'), ('ip_blocked', 'Request blocked by IP allowlist'), ('password_changed', 'Password changed'), ('email_reverified', 'Email re-verified'), ('api_key_created', 'API key created'), ('api_key_revoked', 'API key revoked'), ('api_key_deleted', 'API key deleted')], db_index=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='accounts.marina')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['marina', '-created_at'], name='security_se_marina__000416_idx')],
            },
        ),
    ]
