# Generated by Django 6.0.4 on 2026-04-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarinaMapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_config', to='accounts.marina')),
            ],
        ),
        migrations.CreateModel(
            name='Pier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('cx', models.IntegerField(default=0, help_text='SVG centre-x position')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piers', to='accounts.marina')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('marina', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('side', models.CharField(choices=[('port', 'Port'), ('starboard', 'Starboard')], default='port', max_length=10)),
                ('position_index', models.IntegerField(default=0)),
                ('length_m', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('max_draft_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_beam_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berths', to='accounts.marina')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_berth', to='vessels.vessel')),
                ('pier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berths', to='berths.pier')),
            ],
            options={
                'ordering': ['pier__code', 'position_index'],
                'unique_together': {('marina', 'code')},
            },
        ),
    ]
