# Generated by Django 6.0.4 on 2026-05-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='canvas_height',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='berth',
            name='canvas_rotation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='berth',
            name='canvas_width',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='berth',
            name='canvas_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berth',
            name='canvas_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pier',
            name='canvas_height',
            field=models.FloatField(default=8),
        ),
        migrations.AddField(
            model_name='pier',
            name='canvas_width',
            field=models.FloatField(default=40),
        ),
        migrations.AddField(
            model_name='pier',
            name='canvas_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pier',
            name='canvas_y',
            field=models.FloatField(default=0),
        ),
    ]
