# Generated by Django 6.0.4 on 2026-05-01 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_marina_onboarding_emailverification'),
        ('berths', '0002_berth_canvas_height_berth_canvas_rotation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berth',
            name='canvas_height',
        ),
        migrations.RemoveField(
            model_name='berth',
            name='canvas_width',
        ),
        migrations.RemoveField(
            model_name='pier',
            name='canvas_height',
        ),
        migrations.RemoveField(
            model_name='pier',
            name='canvas_width',
        ),
        migrations.RemoveField(
            model_name='pier',
            name='canvas_x',
        ),
        migrations.RemoveField(
            model_name='pier',
            name='canvas_y',
        ),
        migrations.RemoveField(
            model_name='pier',
            name='cx',
        ),
        migrations.AddField(
            model_name='pier',
            name='polygon_points',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('harbour_master', 'Harbour Master'), ('fuel', 'Fuel Pump'), ('toilets', 'Toilets'), ('showers', 'Showers'), ('restaurant', 'Restaurant'), ('parking', 'Parking'), ('electricity', 'Electricity'), ('water', 'Water'), ('gate', 'Security Gate'), ('waste', 'Waste Disposal'), ('chandlery', 'Chandlery'), ('first_aid', 'First Aid')], max_length=30)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('canvas_x', models.FloatField(blank=True, null=True)),
                ('canvas_y', models.FloatField(blank=True, null=True)),
                ('scale', models.FloatField(default=1.0)),
                ('rotation', models.FloatField(default=0)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='accounts.marina')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
    ]
