# Generated by Django 6.0.4 on 2026-05-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0003_pier_polygon_amenity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['type']},
        ),
        migrations.RemoveField(
            model_name='berth',
            name='canvas_height',
        ),
        migrations.RemoveField(
            model_name='berth',
            name='canvas_width',
        ),
        migrations.AlterField(
            model_name='amenity',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='type',
            field=models.CharField(choices=[('harbour_master', 'Harbour Master'), ('fuel', 'Fuel Pump'), ('toilets', 'Toilets'), ('showers', 'Showers'), ('restaurant', 'Restaurant'), ('parking', 'Parking'), ('electricity', 'Electricity'), ('water', 'Water'), ('gate', 'Security Gate'), ('waste', 'Waste Disposal'), ('chandlery', 'Chandlery'), ('first_aid', 'First Aid')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pier',
            name='polygon_points',
            field=models.JSONField(default=list),
        ),
    ]
