# Generated by Django 6.0.4 on 2026-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0004_remove_berth_canvas_size_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pier',
            name='ghost_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pier',
            name='pier_type',
            field=models.CharField(choices=[('concrete', 'Concrete Pier'), ('pontoon', 'Wooden Pontoon'), ('land', 'Land / Grass')], default='concrete', max_length=20),
        ),
    ]
