# Generated by Django 6.0.4 on 2026-05-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0005_pier_type_ghost_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pier',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
