# Generated by Django 6.0.4 on 2026-05-02 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_marina_onboarding_emailverification'),
        ('berths', '0006_pier_code_max_length_50'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPrefab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pier_type', models.CharField(choices=[('concrete', 'Concrete Pier'), ('pontoon', 'Wooden Pontoon'), ('land', 'Land / Grass')], max_length=20)),
                ('polygon_points', models.JSONField()),
                ('berth_slots', models.JSONField(default=list)),
                ('label_template', models.CharField(blank=True, max_length=50)),
                ('is_base', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefabs', to='accounts.marina')),
            ],
            options={
                'ordering': ['-is_base', 'name'],
            },
        ),
    ]
