# Generated by Django 6.0.4 on 2026-05-02 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0008_seed_base_prefabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='local_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='berth',
            name='local_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='berth',
            name='position_on_parent',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pier',
            name='canvas_h',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='pier',
            name='canvas_w',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='pier',
            name='canvas_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pier',
            name='canvas_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pier',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='berth',
            name='pier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berths', to='berths.pier'),
        ),
    ]
