# Generated by Django 6.0.4 on 2026-05-03 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0009_add_canvas_fields'),
        ('billing', '0008_account_payment_member_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapprefab',
            name='marina',
        ),
        migrations.RemoveField(
            model_name='berth',
            name='canvas_rotation',
        ),
        migrations.RemoveField(
            model_name='berth',
            name='canvas_x',
        ),
        migrations.RemoveField(
            model_name='berth',
            name='canvas_y',
        ),
        migrations.AddField(
            model_name='berth',
            name='pricing_tier',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'berth'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berths', to='billing.chargeableitem'),
        ),
        migrations.AlterField(
            model_name='pier',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='MapPrefab',
        ),
    ]
