# Generated by Django 6.0.4 on 2026-05-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0011_migrate_price_per_night_to_chargeable_items'),
        ('billing', '0008_account_payment_member_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berth',
            name='price_per_night',
        ),
        migrations.AlterField(
            model_name='berth',
            name='pricing_tier',
            field=models.ForeignKey(limit_choices_to={'category': 'berth'}, on_delete=django.db.models.deletion.PROTECT, related_name='berths', to='billing.chargeableitem'),
        ),
    ]
