# Generated by Django 6.0.4 on 2026-05-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0012_remove_berth_price_per_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pier',
            name='canvas_h',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='pier',
            name='canvas_w',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='pier',
            name='pier_type',
            field=models.CharField(choices=[('concrete', 'Concrete Pier'), ('pontoon', 'Wooden Pontoon'), ('steel', 'Steel'), ('land', 'Land / Grass'), ('fuel-dock', 'Fuel Dock'), ('gangway', 'Gangway'), ('ramp', 'Launch Ramp')], default='concrete', max_length=20),
        ),
    ]
