# Generated by Django 6.0.4 on 2026-05-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0015_berth_pricing_tier_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='berth_class',
            field=models.CharField(choices=[('standard', 'Standard'), ('operational', 'Operational')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='berth',
            name='operational_type',
            field=models.CharField(blank=True, choices=[('fuel_dock', 'Fuel Dock')], default='', max_length=30),
        ),
    ]
