# Generated by Django 6.0.4 on 2026-05-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0016_berth_class_operational_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berth',
            name='operational_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('fuel_dock', 'Fuel Dock')], default='', max_length=30),
        ),
    ]
