# Generated by Django 6.0.4 on 2026-05-05 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_marina_wallet_fields'),
        ('berths', '0017_operational_type_add_empty_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('harbour_master', 'Harbour Master'), ('fuel', 'Fuel Pump'), ('toilets', 'Toilets'), ('showers', 'Showers'), ('restaurant', 'Restaurant'), ('parking', 'Parking'), ('electricity', 'Electricity'), ('water', 'Water'), ('gate', 'Security Gate'), ('waste', 'Waste Disposal'), ('chandlery', 'Chandlery'), ('first_aid', 'First Aid')], max_length=30)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('canvas_x', models.FloatField(blank=True, null=True)),
                ('canvas_y', models.FloatField(blank=True, null=True)),
                ('scale', models.FloatField(default=1.0)),
                ('rotation', models.FloatField(default=0)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='accounts.marina')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
    ]
