# Generated by Django 6.0.4 on 2026-05-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0018_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='channel_cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berth',
            name='sales_channel',
            field=models.CharField(choices=[('direct', 'Direct'), ('mysea', 'mySea')], default='direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='pier',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
