# Generated by Django 6.0.4 on 2026-05-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0019_berth_channel_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pier',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
