# Generated by Django 6.0.4 on 2026-05-06 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_marina_stripe_signup_fields'),
        ('berths', '0020_pier_code_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTAConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('inbound_ical_url', models.URLField(blank=True, default='')),
                ('outbound_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('target_pct', models.IntegerField(default=20)),
                ('auto_allocate', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_connections', to='accounts.marina')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('marina', 'slug')},
            },
        ),
    ]
