# Generated by Django 6.0.4 on 2026-05-06 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0021_ota_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otaconnection',
            name='target_pct',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
