# Generated by Django 6.0.4 on 2026-05-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0023_migrate_channel_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berth',
            name='channel_cooldown_until',
        ),
        migrations.RemoveField(
            model_name='berth',
            name='sales_channel',
        ),
        migrations.AddField(
            model_name='berth',
            name='channel_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='berth',
            name='ota_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berths', to='berths.otaconnection'),
        ),
    ]
