# Generated by Django 6.0.4 on 2026-05-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0024_migrate_channel_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berth',
            name='channel_cooldown_until',
        ),
        migrations.RemoveField(
            model_name='berth',
            name='sales_channel',
        ),
    ]
