# Generated by Django 6.0.4 on 2026-05-07 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_marina_channel_fields'),
        ('berths', '0025_berth_remove_old_channel_fields'),
        ('billing', '0011_berth_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerthCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mooring_type', models.CharField(choices=[('finger', 'Finger Pontoon'), ('alongside', 'Alongside'), ('stern_to', 'Stern-to'), ('mooring_ball', 'Mooring Ball')], default='finger', max_length=20)),
                ('amenities', models.JSONField(default=list)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berth_categories', to='accounts.marina')),
                ('pricing_tier', models.ForeignKey(blank=True, limit_choices_to={'category': 'berth'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='berth_categories', to='billing.chargeableitem')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('marina', 'name')},
            },
        ),
        migrations.AddField(
            model_name='berth',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berths', to='berths.berthcategory'),
        ),
    ]
