# Generated by Django 6.0.4 on 2026-05-07 13:30

import django.db.models.deletion
from django.db import migrations, models


def reset_position_on_parent(apps, schema_editor):
    Berth = apps.get_model('berths', 'Berth')
    Berth.objects.update(position_on_parent='')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_marina_channel_fields'),
        ('berths', '0026_berth_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pier',
            name='components',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pier',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(reset_position_on_parent, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='berth',
            name='position_on_parent',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='LogicalPier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pier_type', models.CharField(choices=[('concrete', 'Concrete Pier'), ('pontoon', 'Wooden Pontoon'), ('steel', 'Steel'), ('land', 'Land / Grass'), ('fuel-dock', 'Fuel Dock'), ('gangway', 'Gangway'), ('ramp', 'Launch Ramp')], default='pontoon', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logical_piers', to='accounts.marina')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('marina', 'name')},
            },
        ),
        migrations.AddField(
            model_name='pier',
            name='logical_pier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dock_shapes', to='berths.logicalpier'),
        ),
    ]
