# Generated by Django 6.0.4 on 2026-05-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0030_berth_intelligence_models'),
        ('members', '0006_member_is_archived_member_merged_into_and_more'),
        ('revenue_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berth',
            name='booking_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berths', to='revenue_intelligence.bookingtier'),
        ),
        migrations.AddField(
            model_name='berth',
            name='lease_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='berth',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_berths', to='members.member'),
        ),
    ]
