# Generated by Django 6.0.4 on 2026-05-08 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota_channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otabooking',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_bookings', to='ota_channels.otachannel'),
        ),
    ]
