# Generated by Django 6.0.4 on 2026-04-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_marina_stripe_account_id_marina_vat_rate'),
        ('billing', '0002_rebuild_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('marina', 'invoice_number')},
        ),
    ]
