# Generated by Django 6.0.4 on 2026-05-01 23:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_marina_onboarding_emailverification'),
        ('billing', '0003_invoice_number_unique_per_marina'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='ChargeableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('berth', 'Berth'), ('utility', 'Utility'), ('service', 'Service'), ('retail', 'Retail')], default='service', max_length=20)),
                ('pricing_model', models.CharField(choices=[('flat_fee', 'Flat Fee'), ('per_night', 'Per Night'), ('per_meter_per_night', 'Per Meter Per Night'), ('per_kwh', 'Per kWh'), ('per_hour', 'Per Hour'), ('per_meter_flat', 'Per Meter (flat)')], default='flat_fee', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargeable_items', to='accounts.marina')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='chargeable_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='billing.chargeableitem'),
        ),
    ]
