# Generated by Django 6.0.4 on 2026-05-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_billing_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeableitem',
            name='fuel_dock_type',
            field=models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('pump_out', 'Pump-out')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chargeableitem',
            name='show_in_pos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chargeableitem',
            name='pricing_model',
            field=models.CharField(choices=[('flat_fee', 'Flat Fee'), ('per_night', 'Per Night'), ('per_meter_per_night', 'Per Meter Per Night'), ('per_kwh', 'Per kWh'), ('per_hour', 'Per Hour'), ('per_meter_flat', 'Per Meter (flat)'), ('per_litre', 'Per Litre')], default='flat_fee', max_length=30),
        ),
    ]
