# Generated by Django 6.0.4 on 2026-05-02 22:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_marina_fuel_berths'),
        ('billing', '0006_chargeableitem_fuel_dock_type_and_more'),
        ('members', '0004_member_boater_user'),
        ('staff', '0002_certification_pdf_file_staffmember_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('external_card', 'External Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_payments', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_payments', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.accountpayment')),
            ],
        ),
    ]
