# Generated by Django 6.0.4 on 2026-05-02 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_account_payment_allocation'),
        ('members', '0004_member_boater_user'),
        ('staff', '0002_certification_pdf_file_staffmember_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='accountpayment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_payments', to='members.member'),
        ),
        migrations.AlterField(
            model_name='accountpayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_account_payments', to='staff.staffmember'),
        ),
    ]
