# Generated by Django 6.0.4 on 2026-05-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_account_payment_member_null'),
        ('reservations', '0006_booking_portal_checkin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='reservations.booking'),
        ),
        migrations.AlterField(
            model_name='chargeableitem',
            name='category',
            field=models.CharField(choices=[('berth', 'Berth'), ('utility', 'Utility'), ('service', 'Service'), ('retail', 'Retail'), ('booking_fee', 'Booking Fee')], default='service', max_length=20),
        ),
    ]
