# Generated by Django 6.0.4 on 2026-05-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_chargeableitem_mandatory_transient_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('unpaid', 'Unpaid'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=10),
        ),
    ]
