# Generated by Django 6.0.4 on 2026-05-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_berth_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeableitem',
            name='is_discountable',
            field=models.BooleanField(default=True, help_text='Set False for deposit and carbon-offset items to block coupon/loyalty discounts.'),
        ),
        migrations.AlterField(
            model_name='chargeableitem',
            name='category',
            field=models.CharField(choices=[('berth', 'Berth'), ('utility', 'Utility'), ('service', 'Service'), ('retail', 'Retail'), ('booking_fee', 'Booking Fee'), ('fuel', 'Fuel'), ('repair', 'Repair'), ('course', 'Course'), ('loyalty', 'Loyalty Redemption'), ('subscription', 'Subscription'), ('penalty', 'Penalty'), ('deposit', 'Deposit'), ('rent', 'Rent'), ('offset', 'Carbon Offset'), ('commission', 'Commission'), ('charter', 'Charter Fee')], default='service', max_length=20),
        ),
    ]
