# Generated by Django 6.0.4 on 2026-05-08 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_chargeableitem_is_discountable_and_more'),
        ('harbour', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note')], default='invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='related_invoice',
            field=models.ForeignKey(blank=True, help_text='For credit notes: points to the original invoice being neutralised.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='harbour.shippingagent'),
        ),
        migrations.AlterField(
            model_name='chargeableitem',
            name='category',
            field=models.CharField(choices=[('berth', 'Berth'), ('utility', 'Utility'), ('service', 'Service'), ('retail', 'Retail'), ('booking_fee', 'Booking Fee'), ('fuel', 'Fuel'), ('repair', 'Repair'), ('course', 'Course'), ('loyalty', 'Loyalty Redemption'), ('subscription', 'Subscription'), ('penalty', 'Penalty'), ('deposit', 'Deposit'), ('rent', 'Rent'), ('offset', 'Carbon Offset'), ('commission', 'Commission'), ('charter', 'Charter Fee'), ('harbour_tariff', 'Harbour Tariff')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='chargeableitem',
            name='pricing_model',
            field=models.CharField(choices=[('flat_fee', 'Flat Fee'), ('per_night', 'Per Night'), ('per_meter_per_night', 'Per Meter Per Night'), ('per_kwh', 'Per kWh'), ('per_hour', 'Per Hour'), ('per_meter_flat', 'Per Meter (flat)'), ('per_litre', 'Per Litre'), ('per_week', 'Per Week'), ('per_passenger', 'Per Passenger'), ('per_gross_ton', 'Per Gross Ton'), ('per_ton_distance', 'Per Ton × Distance')], default='flat_fee', max_length=30),
        ),
    ]
