# Generated by Django 6.0.4 on 2026-05-08 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_marinagroup_marina_harbour_master_email_and_more'),
        ('billing', '0013_invoice_invoice_type_invoice_related_invoice_and_more'),
        ('members', '0005_member_sublet_opt_in'),
        ('staff', '0003_staffmember_is_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalate_to', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('referred', 'Referred to Agency')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_escalations', to='staff.staffmember')),
                ('invoices', models.ManyToManyField(blank=True, related_name='debt_escalations', to='billing.invoice')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_escalations', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_escalations', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_method', models.CharField(choices=[('phone', 'Phone Call'), ('email', 'Email'), ('in_person', 'In Person'), ('letter', 'Letter')], max_length=20)),
                ('outcome', models.CharField(choices=[('promise_to_pay', 'Promise to Pay'), ('disputed', 'Disputed'), ('no_contact', 'No Contact Made'), ('paid', 'Paid in Full')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('promised_payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_notes', to='staff.staffmember')),
                ('invoices', models.ManyToManyField(blank=True, related_name='debt_notes', to='billing.invoice')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_notes', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_notes', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DunningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('bounced', 'Bounced')], default='draft', max_length=20)),
                ('demand_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='dunning_letters/')),
                ('send_via', models.CharField(default='email', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dunning_letters', to='staff.staffmember')),
                ('invoices', models.ManyToManyField(blank=True, related_name='dunning_letters', to='billing.invoice')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_letters', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_letters', to='members.member')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DunningTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffmember')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_templates', to='accounts.marina')),
            ],
            options={
                'ordering': ['marina', 'level'],
                'unique_together': {('marina', 'level')},
            },
        ),
    ]
