# Generated by Django 6.0.4 on 2026-05-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_debtescalation_debtnote_dunningletter_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeableitem',
            name='is_upsell_eligible',
            field=models.BooleanField(default=False, help_text='Mark items that can be offered as upsells during booking or check-in.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='tenants.tenantcontact'),
        ),
    ]
