# Generated by Django 6.0.4 on 2026-05-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_marinagroup_additions'),
        ('billing', '0015_chargeableitem_is_upsell_eligible_invoice_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='accounts.marina')),
            ],
            options={
                'ordering': ['-rate'],
                'unique_together': {('marina', 'name')},
            },
        ),
    ]
