# Generated by Django 6.0.4 on 2026-05-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_add_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeableitem',
            name='tax_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chargeable_items', to='billing.taxrate'),
        ),
    ]
