# Generated by Django 6.0.4 on 2026-05-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_taxrate_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeableitem',
            name='tax_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chargeable_items', to='billing.taxrate'),
        ),
        migrations.RemoveField(
            model_name='chargeableitem',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vat_rate',
        ),
    ]
