# Generated by Django 6.0.4 on 2026-05-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_taxrate_cleanup'),
        ('reservations', '0016_backfill_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='reservations.reservation'),
        ),
    ]
