# Generated by Django 6.0.5 on 2026-05-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_invoice_reservation_backfill'),
        ('staff', '0003_staffmember_is_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source', models.CharField(db_index=True, max_length=30)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chargeableitem',
            name='qty_variable',
            field=models.BooleanField(default=False, help_text='If True, the Quick Charge UI renders a quantity stepper; otherwise the item is single-tap qty=1.'),
        ),
        migrations.AddField(
            model_name='chargeableitem',
            name='show_in_quick_charge',
            field=models.BooleanField(default=False, help_text='Surfaces this item in the staff Quick Charge PWA grid.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_intent_status',
            field=models.CharField(blank=True, default='', help_text="Stripe PaymentIntent status snapshot: '', 'pending', 'processing', 'requires_action', 'succeeded', 'canceled'. Quick Charge blocks new lines while in-flight.", max_length=30),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_invoice_lines', to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='undo_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
