# Generated by Django 6.0.5 on 2026-05-16 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_backfill_email_verified_at'),
        ('billing', '0022_idempotencykey_chargeableitem_qty_variable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('stripe_refund_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(default='eur', max_length=10)),
                ('reason', models.CharField(choices=[('duplicate', 'Duplicate'), ('fraudulent', 'Fraudulent'), ('requested_by_customer', 'Requested by Customer'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('requires_action', 'Requires Action'), ('manual_required', 'Manual Required')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='billing.invoice')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='accounts.marina')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
