# Generated by Django 4.2.29 on 2026-04-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
