# Generated by Django 6.0.4 on 2026-05-12 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenancetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='defect',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.defect'),
        ),
    ]
