# Generated by Django 4.2.29 on 2026-04-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='operations_paused',
            field=models.BooleanField(default=False),
        ),
    ]
