# Generated by Django 6.0.4 on 2026-04-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_marina_operations_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='booking_mode',
            field=models.CharField(choices=[('manual_approval', 'Manual Approval'), ('auto_tetris', 'Auto-Tetris')], default='manual_approval', max_length=20),
        ),
    ]
