# Generated by Django 6.0.4 on 2026-04-30 16:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_magictoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marina',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
