# Generated by Django 6.0.4 on 2026-04-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_marina_stripe_account_id_marina_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='marina',
            name='max_staff',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='marina',
            name='mrr_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='next_renewal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='marina',
            name='suspend_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='trial_ends',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('support', 'Support')], max_length=20),
        ),
    ]
