# Generated by Django 6.0.4 on 2026-05-03 06:16

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    import uuid
    Marina = apps.get_model('accounts', 'Marina')
    for marina in Marina.objects.all():
        base = slugify(marina.name)[:96] or uuid.uuid4().hex[:8]
        slug = base
        n = 1
        while Marina.objects.filter(slug=slug).exclude(pk=marina.pk).exists():
            slug = f'{base}-{n}'
            n += 1
        marina.slug = slug
        marina.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_marina_fuel_berths'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='marina',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
