# Generated by Django 6.0.4 on 2026-05-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_marina_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='module_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Per-module access for staff users. Keys are module IDs; value false blocks access. Empty dict means all modules allowed (default).'),
        ),
    ]
