# Generated by Django 6.0.4 on 2026-05-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_marina_custom_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='waiver_template_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='wallet_gate_codes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='marina',
            name='wallet_harbour_master_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='wallet_office_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='wallet_vhf_channel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='wallet_wifi_network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='wallet_wifi_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
