# Generated by Django 6.0.4 on 2026-05-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_marina_wallet_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='auto_allocate_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marina',
            name='mysea_ical_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marina',
            name='mysea_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='mysea_target_pct',
            field=models.IntegerField(default=20),
        ),
    ]
