# Generated by Django 6.0.4 on 2026-05-05 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_marina_channel_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marina',
            name='mysea_target_pct',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
