# Generated by Django 6.0.4 on 2026-05-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_mysea_target_pct_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='abandon_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marina',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='marina',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
    ]
