# Generated by Django 6.0.4 on 2026-05-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_marina_stripe_signup_fields'),
        ('berths', '0024_migrate_channel_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marina',
            name='auto_allocate_inventory',
        ),
        migrations.RemoveField(
            model_name='marina',
            name='mysea_ical_url',
        ),
        migrations.RemoveField(
            model_name='marina',
            name='mysea_last_synced',
        ),
        migrations.RemoveField(
            model_name='marina',
            name='mysea_target_pct',
        ),
    ]
