# Generated by Django 6.0.4 on 2026-05-08 11:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_marina_no_show_grace_minutes'),
        ('billing', '0013_invoice_invoice_type_invoice_related_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarinaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='marina',
            name='harbour_master_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='marina',
            name='points_earn_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='marina',
            name='points_to_currency_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='marina',
            name='referral_referee_benefit_type',
            field=models.CharField(default='discount', max_length=20),
        ),
        migrations.AddField(
            model_name='marina',
            name='referral_referee_benefit_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='marina',
            name='referral_referrer_benefit_type',
            field=models.CharField(default='points', max_length=20),
        ),
        migrations.AddField(
            model_name='marina',
            name='referral_referrer_benefit_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='marina',
            name='warranty_cogs_offset_account',
            field=models.ForeignKey(blank=True, help_text='GL account for COGS offset on warranty repairs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.chargeableitem'),
        ),
        migrations.AddField(
            model_name='marina',
            name='warranty_gl_account',
            field=models.ForeignKey(blank=True, help_text='GL account for warranty reimbursement income.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.chargeableitem'),
        ),
        migrations.CreateModel(
            name='MarinaGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.marinagroup')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='accounts.marina')),
            ],
            options={
                'unique_together': {('group', 'marina')},
            },
        ),
        migrations.CreateModel(
            name='MarinaGroupUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('admin', 'Admin')], default='viewer', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.marinagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
