# Generated by Django 6.0.4 on 2026-05-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_marinagroup_marina_harbour_master_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='support_access_granted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
