# Generated by Django 6.0.4 on 2026-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_marina_dropboxsign_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
