# Generated by Django 6.0.4 on 2026-05-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_marina_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinagroup',
            name='base_currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='marinagroup',
            name='billing_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='marinagroup',
            name='max_marinas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marinagroup',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
