# Generated by Django 6.0.4 on 2026-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_marinagroup_additions'),
    ]

    operations = [
        migrations.AddField(
            model_name='marinagroup',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
