# Generated by Django 6.0.4 on 2026-05-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_vat_number_to_marina_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='app_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
