# Generated by Django 6.0.4 on 2026-05-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_marina_app_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='notification_from_email',
            field=models.EmailField(blank=True, help_text='From address used in all outgoing marina emails.', max_length=254),
        ),
        migrations.AddField(
            model_name='marina',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='SMTP host (leave blank to use platform default).', max_length=255),
        ),
        migrations.AddField(
            model_name='marina',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Stored in plaintext — use environment secrets for production deployments.', max_length=255),
        ),
        migrations.AddField(
            model_name='marina',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, help_text='SMTP port, e.g. 587.', null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
