# Generated by Django 6.0.5 on 2026-05-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_data_export'),
        ('accounts', '0028_marina_ais_fields'),
        ('accounts', '0028_marina_docusign_jwt_fields'),
        ('accounts', '0029_encrypt_marina_credentials'),
    ]

    operations = [
    ]
