# Generated by Django 6.0.5 on 2026-05-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_merge_20260515_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='require_mfa_for_managers',
            field=models.BooleanField(default=False),
        ),
    ]
