# Generated by Django 6.0.5 on 2026-05-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_backfill_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='sms_unit_cost_cents',
            field=models.IntegerField(default=250, help_text='Per-SMS-segment cost in 1/100 cents (i.e. 250 = $0.025 = 2.5¢). Used by Broadcast Center cost previews.'),
        ),
    ]
