# Generated by Django 6.0.5 on 2026-05-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_merge_max_waitlist_declines_sms_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='charge_full_season_on_mid_start',
            field=models.BooleanField(default=False, help_text='When True, a lease that starts mid-season is billed at the full season_total instead of being pro-rated by remaining calendar days (spec §6.1).'),
        ),
    ]
