# Generated by Django 6.0.5 on 2026-05-17 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_merge_max_waitlist_declines_sms_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='billing_admin_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marina',
            name='billing_admin_override_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='billing_admin_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='billing_admin_override_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='billing_admin_override_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marina',
            name='billing_failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marina',
            name='billing_grace_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='billing_last_email_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='billing_last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='billing_state',
            field=models.CharField(choices=[('current', 'Current'), ('past_due', 'Past Due'), ('grace', 'Grace'), ('restricted', 'Restricted'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('manual', 'Manual Contract')], default='current', help_text='Automatic platform-billing lifecycle. Independent of Marina.status.', max_length=20),
        ),
        migrations.AddField(
            model_name='marina',
            name='billing_state_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='manual_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marina',
            name='manual_contract_invoice_terms',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='marina',
            name='manual_contract_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='manual_contract_po_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marina',
            name='manual_contract_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marina',
            name='manual_contract_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='manual_contract_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='manual_contract_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marina',
            name='manual_contract_signed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marina',
            name='manual_contract_signed_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
