# Generated by Django 6.0.5 on 2026-05-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_merge_billing_gates_and_seasonal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marina',
            name='max_draft',
        ),
        migrations.RemoveField(
            model_name='marina',
            name='max_loa',
        ),
    ]
