# Generated by Django 6.0.4 on 2026-05-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_marina_max_draft_remove_marina_max_loa'),
    ]

    operations = [
        migrations.AddField(
            model_name='marina',
            name='booking_terms_pdf_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='marina',
            name='booking_terms_version',
            field=models.CharField(blank=True, default='1.0', max_length=32),
        ),
        migrations.AddField(
            model_name='marina',
            name='requires_air_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marina',
            name='requires_insurance_at_booking',
            field=models.BooleanField(default=False),
        ),
    ]
