# Generated by Django 6.0.4 on 2026-04-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('starters', 'Starters'), ('mains', 'Mains'), ('desserts', 'Desserts'), ('drinks', 'Drinks')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('prep_time', models.IntegerField(default=15, help_text='minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='accounts.marina')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covers', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_prep', 'In Prep'), ('ready', 'Ready'), ('served', 'Served')], default='waiting', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.marina')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_prep', 'In Prep'), ('ready', 'Ready'), ('served', 'Served')], default='waiting', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order')),
            ],
        ),
        migrations.CreateModel(
            name='RestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=100)),
                ('capacity', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('free', 'Free'), ('seated', 'Seated'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning')], default='free', max_length=20)),
                ('server', models.CharField(blank=True, max_length=200)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_tables', to='accounts.marina')),
            ],
            options={
                'unique_together': {('marina', 'number')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.resttable'),
        ),
    ]
