# Generated by Django 6.0.4 on 2026-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyberthconfig',
            name='eligible_booking_types',
            field=models.CharField(blank=True, default='transient', help_text='Comma-separated booking types eligible for hourly pricing.', max_length=200),
        ),
        migrations.AddField(
            model_name='yieldrule',
            name='applies_to_booking_type',
            field=models.CharField(blank=True, default='', help_text='Booking type this rule applies to, e.g. "transient". Empty = all types.', max_length=30),
        ),
    ]
