# Generated by Django 6.0.4 on 2026-04-30 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_member_boater_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('day_trip', 'Day Trip'), ('overnight', 'Overnight'), ('extended', 'Extended')], max_length=20)),
                ('departure', models.DateField()),
                ('return_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_reports', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CraneRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('launch', 'Launch'), ('haul_out', 'Haul-out'), ('both', 'Launch & Haul-out')], max_length=20)),
                ('requested_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crane_requests', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
