# Generated by Django 6.0.4 on 2026-05-08 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_marinagroup_marina_harbour_master_email_and_more'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingWidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#1a3a5c', max_length=7)),
                ('button_text', models.CharField(default='Check Availability', max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('show_extras', models.JSONField(default=list)),
                ('allowed_origins', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_config', to='accounts.marina')),
            ],
        ),
    ]
