# Generated by Django 6.0.4 on 2026-05-08 10:05

import apps.accounting.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meterreading',
            new_name='utilities_m_meter_i_dd771c_idx',
            old_name='utilities_m_meter_i_idx',
        ),
        migrations.AlterField(
            model_name='utilityintegration',
            name='credentials',
            field=apps.accounting.fields.EncryptedJSONField(default=dict, help_text='Encrypted dict: api_key, base_url, etc.'),
        ),
    ]
