# Generated by Django 6.0.4 on 2026-05-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_marina_app_config'),
        ('billing', '0021_invoice_reservation_backfill'),
        ('members', '0006_member_is_archived_member_merged_into_and_more'),
        ('utilities', '0002_rename_utilities_m_meter_i_idx_utilities_m_meter_i_dd771c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUtilityCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh_delta', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('m3_delta', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rollover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_utility_charges', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_utility_charges', to='members.member')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_charges', to='utilities.smartmeter')),
                ('meter_reading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_charges', to='utilities.meterreading')),
                ('swept_to_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_charges', to='billing.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
