# Generated by Django 6.0.4 on 2026-05-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds MarinaMeterWebhookKey + hashed device-token fields on SmartMeter,
    and converts MeterReading.(meter, recorded_at) to a unique constraint
    so the new bulk ingest endpoints can use bulk_create(ignore_conflicts=True).

    PRE-DEPLOY CHECK — run this on every production DB before applying:

        SELECT meter_id, recorded_at, count(*)
        FROM utilities_meterreading
        GROUP BY meter_id, recorded_at HAVING count(*) > 1;

    If any rows are returned, dedupe them before migrating (the unique
    constraint will otherwise fail).
    """

    dependencies = [
        ('accounts', '0025_marina_app_config'),
        ('utilities', '0003_pending_utility_charge'),
    ]

    operations = [
        # -----------------------------------------------------------------
        # SmartMeter — four new hashed-token / hardware-id fields
        # -----------------------------------------------------------------
        migrations.AddField(
            model_name='smartmeter',
            name='hardware_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Public identifier the device sends in X-Hardware-ID',
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='smartmeter',
            name='device_token_prefix',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='smartmeter',
            name='device_token_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='smartmeter',
            name='device_token_last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # -----------------------------------------------------------------
        # MeterReading — swap composite index for unique constraint
        # -----------------------------------------------------------------
        migrations.RemoveIndex(
            model_name='meterreading',
            name='utilities_m_meter_i_dd771c_idx',
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.UniqueConstraint(
                fields=['meter', 'recorded_at'],
                name='utilities_meterreading_meter_recorded_uniq',
            ),
        ),

        # -----------------------------------------------------------------
        # MarinaMeterWebhookKey — new model
        # -----------------------------------------------------------------
        migrations.CreateModel(
            name='MarinaMeterWebhookKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_prefix', models.CharField(blank=True, db_index=True, max_length=16)),
                ('key_hash', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('marina', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='meter_webhook_key',
                    to='accounts.marina',
                )),
            ],
        ),
    ]
