# Generated by Django 6.0.4 on 2026-04-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('member_type', models.CharField(choices=[('seasonal', 'Seasonal'), ('transient', 'Transient'), ('associate', 'Associate')], default='seasonal', max_length=20)),
                ('insurance_status', models.CharField(choices=[('valid', 'Valid'), ('due_soon', 'Due Soon'), ('expired', 'Expired'), ('missing', 'Missing')], default='valid', max_length=20)),
                ('docs_status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('missing', 'Missing')], default='complete', max_length=20)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.marina')),
            ],
        ),
    ]
