# Generated by Django 4.2.29 on 2026-04-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_address_member_address_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['name']},
        ),
    ]
