# Generated by Django 6.0.4 on 2026-05-08 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_marinagroup_marina_harbour_master_email_and_more'),
        ('members', '0005_member_sublet_opt_in'),
        ('reservations', '0012_booking_track2_fields'),
        ('staff', '0003_staffmember_is_contractor'),
        ('vessels', '0004_alter_vessel_options_alter_vesselcertificate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_duplicates', to='members.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False, help_text='Member has opted in to receive WhatsApp messages.'),
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('portal_login_30d', models.BooleanField(default=False)),
                ('email_opens_30d', models.IntegerField(default=0)),
                ('booking_widget_14d', models.BooleanField(default=False)),
                ('vessel_loa_match', models.BooleanField(default=False)),
                ('recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_scores', to='accounts.marina')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_score', to='members.member')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='SecondaryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('routing', models.CharField(choices=[('invoices', 'Invoices'), ('general', 'General Correspondence'), ('emergency', 'Emergency')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_contacts', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_contacts', to='members.member')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_contacts', to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nps_score', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('token_used', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='reservations.booking')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='members.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_rule', models.CharField(choices=[('email', 'Matching Email'), ('phone', 'Matching Phone'), ('vessel_name', 'Vessel Name + Similar Member Name')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('merged', 'Merged'), ('dismissed', 'Dismissed (Not a Duplicate)')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags', to='accounts.marina')),
                ('member_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags_as_a', to='members.member')),
                ('member_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags_as_b', to='members.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_duplicate_flags', to='staff.staffmember')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('member_a', 'member_b')},
            },
        ),
    ]
