# Generated by Django 6.0.5 on 2026-05-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_is_archived_member_merged_into_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='broadcast_opt_in',
            field=models.BooleanField(default=True, help_text='Member is opted in to receive operational broadcast SMS/email. Flipped to False automatically when an inbound STOP/UNSUBSCRIBE keyword arrives on the Twilio inbound SMS webhook.'),
        ),
    ]
