# Generated by Django 6.0.5 on 2026-05-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_is_archived_member_merged_into_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tax_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='tax_exempt_certificate_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='tax_exempt_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
