# Generated by Django 6.0.4 on 2026-04-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('members', '0001_initial'),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('lease', 'Lease'), ('insurance', 'Insurance'), ('waiver', 'Waiver'), ('other', 'Other')], default='other', max_length=20)),
                ('pages', models.IntegerField(default=1)),
                ('fields_count', models.IntegerField(default=0)),
                ('uses_count', models.IntegerField(default=0)),
                ('last_used', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_templates', to='accounts.marina')),
            ],
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reminders_sent', models.IntegerField(default=0)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='accounts.marina')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.doctemplate')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vessels.vessel')),
            ],
        ),
    ]
