# Generated by Django 4.2.29 on 2026-04-29 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vessels', '0004_alter_vessel_options_alter_vesselcertificate_options'),
        ('members', '0003_alter_member_options_alter_segment_options'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='envelope',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AddField(
            model_name='doctemplate',
            name='dropboxsign_template_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='doctemplate',
            name='file',
            field=models.FileField(blank=True, upload_to='doc_templates/'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='dropboxsign_request_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('insurance', 'Insurance'), ('registration', 'Registration')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='member_docs/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_upload', 'Pending Upload'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('due_soon', 'Due Soon'), ('expired', 'Expired')], default='pending_upload', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_documents', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
