# Generated by Django 6.0.4 on 2026-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_doctemplate_options_alter_envelope_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctemplate',
            name='category',
            field=models.CharField(choices=[('lease', 'Lease'), ('insurance', 'Insurance'), ('waiver', 'Waiver'), ('charter_agreement', 'Charter Agreement'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
