# Generated by Django 6.0.4 on 2026-05-11 13:08

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0021_marina_dropboxsign_fields'),
        ('search', '0001_enable_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.PositiveIntegerField()),
                ('search_text', models.TextField()),
                ('display_label', models.CharField(max_length=300)),
                ('display_sub', models.CharField(blank=True, max_length=300)),
                ('screen', models.CharField(max_length=50)),
                ('link_id', models.PositiveIntegerField(blank=True, null=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='accounts.marina')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='search_idx_trgm', opclasses=['gin_trgm_ops'])],
                'unique_together': {('target_model', 'target_id')},
            },
        ),
    ]
