# Generated by Django 6.0.4 on 2026-05-08 08:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_remove_marina_channel_fields'),
        ('billing', '0012_chargeableitem_is_discountable_and_more'),
        ('members', '0004_member_boater_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('points_balance', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_memberships', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_memberships', to='members.member')),
            ],
            options={
                'ordering': ['-lifetime_points'],
                'unique_together': {('marina', 'member')},
            },
        ),
        migrations.CreateModel(
            name='MemberCreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to='members.member')),
            ],
            options={
                'unique_together': {('marina', 'member')},
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=2, help_text='Positive = top-up, negative = spend.', max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_credit_transactions', to='billing.invoice')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.membercreditaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positive = earn, negative = burn.')),
                ('reason', models.CharField(choices=[('booking_earn', 'Booking Earn'), ('referral_earn', 'Referral Earn'), ('bonus_earn', 'Bonus Earn'), ('redemption', 'Redemption'), ('expiry', 'Expiry'), ('admin_adjust', 'Admin Adjustment'), ('coupon_earn', 'Coupon Earn')], max_length=30)),
                ('reference', models.CharField(blank=True, help_text='e.g. booking ID, referral code used', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltymembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('reward_points', models.IntegerField(default=500, help_text='Points awarded to referrer on conversion.')),
                ('referee_reward_points', models.IntegerField(default=250, help_text='Points awarded to the referee.')),
                ('uses_remaining', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to='members.member')),
            ],
            options={
                'unique_together': {('marina', 'code'), ('marina', 'member')},
            },
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_uses', models.IntegerField(blank=True, help_text='Null = unlimited.', null=True)),
                ('uses_count', models.IntegerField(default=0)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_categories', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_codes', to='accounts.marina')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('marina', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ReferralConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_conversions', to='members.member')),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='loyalty.referralcode')),
            ],
            options={
                'unique_together': {('referral_code', 'referee')},
            },
        ),
    ]
