# Generated by Django 6.0.4 on 2026-05-08 11:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_marinagroup_marina_harbour_master_email_and_more'),
        ('billing', '0015_chargeableitem_is_upsell_eligible_invoice_tenant'),
        ('loyalty', '0001_initial'),
        ('members', '0006_member_is_archived_member_merged_into_and_more'),
        ('reservations', '0013_booking_dynamic_price_applied_booking_end_time_and_more'),
        ('staff', '0003_staffmember_is_contractor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referralconversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='referralconversion',
            name='referee',
        ),
        migrations.RemoveField(
            model_name='referralconversion',
            name='referral_code',
        ),
        migrations.AlterModelOptions(
            name='loyaltymembership',
            options={},
        ),
        migrations.RemoveField(
            model_name='loyaltymembership',
            name='lifetime_points',
        ),
        migrations.RemoveField(
            model_name='loyaltymembership',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='referralcode',
            name='referee_reward_points',
        ),
        migrations.RemoveField(
            model_name='referralcode',
            name='reward_points',
        ),
        migrations.RemoveField(
            model_name='referralcode',
            name='uses_remaining',
        ),
        migrations.AddField(
            model_name='loyaltymembership',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltymembership',
            name='lifetime_spend',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='loyaltymembership',
            name='qualifying_stays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loyaltymembership',
            name='tier_achieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loyaltymembership',
            name='tier_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='referee_benefit_type',
            field=models.CharField(default='discount', max_length=20),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='referee_benefit_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='referrer_benefit_type',
            field=models.CharField(default='points', max_length=20),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='referrer_benefit_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='loyaltymembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_membership', to='members.member'),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to='members.member'),
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=0)),
                ('qualification_basis', models.CharField(choices=[('cumulative_spend', 'Cumulative Spend (€)'), ('number_of_stays', 'Number of Stays'), ('years_of_membership', 'Years of Membership')], max_length=30)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('berth_discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('priority_berth_allocation', models.BooleanField(default=False)),
                ('complimentary_services', models.JSONField(blank=True, default=list)),
                ('requalification_policy', models.CharField(choices=[('permanent', 'Held Permanently Once Achieved'), ('annual', 'Must Re-qualify Each Calendar Year')], default='permanent', max_length=20)),
                ('grace_period_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_tiers', to='accounts.marina')),
            ],
            options={
                'ordering': ['marina', 'rank'],
                'unique_together': {('marina', 'rank')},
            },
        ),
        migrations.AlterField(
            model_name='loyaltymembership',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='loyalty.loyaltytier'),
        ),
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('earn', 'Points Earned'), ('redeem', 'Points Redeemed'), ('expire', 'Points Expired'), ('adjust', 'Manual Adjustment'), ('referral', 'Referral Bonus')], max_length=20)),
                ('points', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='staff.staffmember')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='billing.invoice')),
                ('line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_redemption', to='billing.invoicelineitem')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='loyalty.loyaltymembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_status', models.CharField(choices=[('pending', 'Pending First Booking'), ('applied', 'Benefit Applied'), ('rejected', 'Rejected (Ineligible)')], default='pending', max_length=20)),
                ('referrer_benefit_applied_at', models.DateTimeField(blank=True, null=True)),
                ('referee_benefit_applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_use', to='reservations.booking')),
                ('referee_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_uses', to='members.member')),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='loyalty.referralcode')),
            ],
        ),
        migrations.DeleteModel(
            name='PointTransaction',
        ),
        migrations.DeleteModel(
            name='ReferralConversion',
        ),
    ]
