# Generated by Django 6.0.4 on 2026-05-08 10:05

from django.db import migrations


def _rename_index(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER INDEX activities_assetres_asset_idx'
            ' RENAME TO activities__asset_i_efcaf7_idx;'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        # Index rename is PostgreSQL-only — the index was never created on SQLite.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='assetreservation',
                    new_name='activities__asset_i_efcaf7_idx',
                    old_name='activities_assetres_asset_idx',
                ),
            ],
            database_operations=[
                migrations.RunPython(_rename_index, migrations.RunPython.noop),
            ],
        ),
    ]
