# Generated by Django 6.0.5 on 2026-05-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_activities_assetres_asset_idx_activities__asset_i_efcaf7_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='activities.activity')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('activity', 'weekday', 'start_time')},
            },
        ),
    ]
