# Generated by Django 6.0.5 on 2026-05-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activitytimeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitybooking',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='confirmed', max_length=20),
        ),
    ]
