# Generated by Django 6.0.4 on 2026-05-08 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0019_marinagroup_marina_harbour_master_email_and_more'),
        ('billing', '0014_debtescalation_debtnote_dunningletter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_ref', models.CharField(max_length=50)),
                ('unit_type', models.CharField(choices=[('chandlery', 'Chandlery / Marine Shop'), ('workshop', 'Workshop'), ('office', 'Office Suite'), ('storage', 'Dry Storage Unit'), ('retail', 'Retail Unit'), ('food_kiosk', 'Food & Beverage Kiosk Plot'), ('parking_bay', 'Car Parking Bay'), ('trailer_store', 'Boat Trailer Storage')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('has_power', models.BooleanField(default=False)),
                ('has_water', models.BooleanField(default=False)),
                ('has_broadband', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_units', to='accounts.marina')),
            ],
            options={
                'ordering': ['unit_type', 'unit_ref'],
                'unique_together': {('marina', 'unit_ref')},
            },
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('notice', 'Notice Period'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.IntegerField(default=28)),
                ('permitted_use', models.CharField(blank=True, max_length=500)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('break_clause_date', models.DateField(blank=True, null=True)),
                ('break_clause_notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit_chargeable_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'deposit'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_tenancies', to='billing.chargeableitem')),
                ('deposit_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_tenancy', to='billing.invoice')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='accounts.marina')),
                ('rent_chargeable_item', models.ForeignKey(blank=True, limit_choices_to={'category': 'rent'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='billing.chargeableitem')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='tenants.commercialunit')),
            ],
            options={
                'ordering': ['-lease_start'],
            },
        ),
        migrations.CreateModel(
            name='TenancyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('lease_agreement', 'Lease Agreement'), ('guarantor', 'Guarantor Document'), ('planning_permission', 'Planning Permission'), ('compliance_cert', 'Compliance Certificate'), ('insurance', 'Insurance Certificate'), ('correspondence', 'Correspondence'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='tenancy_docs/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancy_documents', to='accounts.marina')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenancy')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TenancyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('rent_review', 'Rent Review'), ('lease_renewal', 'Lease Renewal'), ('compliance', 'Compliance Check'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenancy_tasks', to=settings.AUTH_USER_MODEL)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancy_tasks', to='accounts.marina')),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tenants.tenancy')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('is_company', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_contacts', to='accounts.marina')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='tenancy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='tenants.tenantcontact'),
        ),
        migrations.CreateModel(
            name='RentScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_ref', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_pro_rata', models.BooleanField(default=False)),
                ('pro_rata_days', models.PositiveIntegerField(blank=True, null=True)),
                ('pro_rata_total_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_schedule_entry', to='billing.invoice')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_schedule_entries', to='accounts.marina')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='tenants.tenancy')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('tenancy', 'period_ref')},
            },
        ),
    ]
