# Generated by Django 6.0.5 on 2026-05-16 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_marina_sms_unit_cost_cents'),
        ('communications', '0002_messagetemplate'),
        ('members', '0007_member_broadcast_opt_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('cohort_filter', models.JSONField(blank=True, default=dict)),
                ('previewed_count', models.IntegerField(blank=True, null=True)),
                ('cost_estimate_cents', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('previewed', 'Previewed'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previewed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='accounts.marina')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opted_out', 'Opted Out'), ('skipped_no_address', 'Skipped (No Address)')], default='pending', max_length=30)),
                ('failed_reason', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.broadcast')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_recipients', to='members.member')),
                ('message_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_recipients', to='communications.messagelog')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['broadcast', 'status'], name='communicati_broadca_4c744c_idx')],
            },
        ),
    ]
