# Generated by Django 6.0.4 on 2026-04-28 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_initial'),
        ('members', '0001_initial'),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelDockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_description', models.CharField(blank=True, max_length=300)),
                ('guest_phone', models.CharField(blank=True, max_length=50)),
                ('fuel_type', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('pump_out', 'Pump-out')], max_length=20)),
                ('estimated_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actual_litres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_per_litre', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('next', 'Next'), ('service', 'Service'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('fuel_berth', models.CharField(blank=True, max_length=20)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('service_start', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pos_paid', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='billing.invoice')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_queue', to='accounts.marina')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='members.member')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_entries', to='vessels.vessel')),
            ],
            options={
                'ordering': ['arrived_at'],
            },
        ),
    ]
