# Generated by Django 6.0.4 on 2026-05-04 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berths', '0017_operational_type_add_empty_choice'),
        ('fuel_dock', '0001_initial'),
    ]

    operations = [
        # Step 1: Add a temporary nullable text column for the new FK id,
        # set it NULL for all rows (since no existing string maps to a real Berth),
        # then swap the column.  On SQLite we use SeparateDatabaseAndState so
        # we control the raw SQL ourselves instead of relying on AlterField's
        # table-rebuild (which chokes on '' → INTEGER FK).
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    # SQLite doesn't support ALTER COLUMN, so we recreate the table.
                    # We copy all columns but leave fuel_berth_id as NULL.
                    sql="""
                        CREATE TABLE fuel_dock_fueldockentry_new (
                            id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                            marina_id INTEGER NOT NULL REFERENCES accounts_marina (id),
                            vessel_id INTEGER NULL REFERENCES vessels_vessel (id),
                            member_id INTEGER NULL REFERENCES members_member (id),
                            guest_description VARCHAR(300) NOT NULL,
                            guest_phone VARCHAR(50) NOT NULL,
                            fuel_type VARCHAR(20) NOT NULL,
                            estimated_litres DECIMAL(8, 2) NULL,
                            actual_litres DECIMAL(8, 2) NULL,
                            price_per_litre DECIMAL(6, 4) NULL,
                            total_amount DECIMAL(10, 2) NULL,
                            status VARCHAR(20) NOT NULL,
                            fuel_berth_id INTEGER NULL REFERENCES berths_berth (id),
                            arrived_at DATETIME NOT NULL,
                            service_start DATETIME NULL,
                            completed_at DATETIME NULL,
                            invoice_id INTEGER NULL REFERENCES billing_invoice (id),
                            pos_paid BOOL NOT NULL
                        );
                        INSERT INTO fuel_dock_fueldockentry_new (
                            id, marina_id, vessel_id, member_id,
                            guest_description, guest_phone,
                            fuel_type, estimated_litres, actual_litres,
                            price_per_litre, total_amount,
                            status, fuel_berth_id,
                            arrived_at, service_start, completed_at,
                            invoice_id, pos_paid
                        )
                        SELECT
                            id, marina_id, vessel_id, member_id,
                            guest_description, guest_phone,
                            fuel_type, estimated_litres, actual_litres,
                            price_per_litre, total_amount,
                            status, NULL,
                            arrived_at, service_start, completed_at,
                            invoice_id, pos_paid
                        FROM fuel_dock_fueldockentry;
                        DROP TABLE fuel_dock_fueldockentry;
                        ALTER TABLE fuel_dock_fueldockentry_new RENAME TO fuel_dock_fueldockentry;
                    """,
                    reverse_sql=migrations.RunSQL.noop,  # intentionally irreversible
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='fueldockentry',
                    name='fuel_berth',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='fuel_entries',
                        to='berths.berth',
                    ),
                ),
            ],
        ),
    ]
