# Generated by Django 6.0.5 on 2026-05-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_dock', '0004_fuelpricechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelpricechange',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
