# Generated by Django 6.0.5 on 2026-05-17 12:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0036_marina_charge_full_season_on_mid_start'),
        ('berths', '0032_berthcategory_tagline_highlights'),
        ('billing', '0023_refund'),
        ('members', '0008_merge_broadcast_opt_in_tax_exempt'),
        ('vessels', '0004_alter_vessel_options_alter_vesselcertificate_options'),
        ('waitlist', '0002_offer_reminder_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('lump_sum', 'Lump Sum'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('instalment_count', models.PositiveIntegerField(default=1)),
                ('first_due_offset_days', models.IntegerField(default=0, help_text='Days after lease.start_date until instalment #1 falls due.')),
                ('deposit_first', models.BooleanField(default=True, help_text='If True, the deposit is a separate first invoice.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalment_plans', to='accounts.marina')),
            ],
            options={
                'ordering': ['marina', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BerthLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('deposit_paid', 'Deposit Paid'), ('active', 'Active'), ('ending', 'Ending'), ('ended', 'Ended'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled'), ('defaulted', 'Defaulted')], default='offered', max_length=20)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('at_risk', models.BooleanField(default=False, help_text='Spec §6.3 — flagged at Day+14 of missed instalment.')),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_forfeited', models.BooleanField(default=False, help_text='Spec §9.2 — deposit auto-forfeited on default transition.')),
                ('renewal_offered_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_response', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('no_response', 'No Response')], default='pending', max_length=20)),
                ('auto_renewal_enabled', models.BooleanField(default=False)),
                ('tax_exempt_override', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('waitlist_offer', 'Waitlist Offer'), ('renewal', 'Renewal'), ('migrated_legacy', 'Migrated From Legacy Booking')], default='manual', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('berth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='berths.berth')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leases', to=settings.AUTH_USER_MODEL)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='accounts.marina')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='members.member')),
                ('prior_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='seasons.berthlease')),
                ('vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='vessels.vessel')),
                ('waitlist_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='waitlist.waitlistoffer')),
                ('instalment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='seasons.instalmentplan')),
            ],
            options={
                'ordering': ['-start_date', 'berth__code'],
            },
        ),
        migrations.CreateModel(
            name='LeaseVesselChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_vessel_changes', to=settings.AUTH_USER_MODEL)),
                ('from_vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_lease_events', to='vessels.vessel')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_changes', to='seasons.berthlease')),
                ('to_vessel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_lease_events', to='vessels.vessel')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season_type', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('annual', 'Annual'), ('custom', 'Custom')], default='summer', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_default_for_new_leases', models.BooleanField(default=False)),
                ('auto_renewal_enabled', models.BooleanField(default=False)),
                ('waitlist_drain_priority', models.IntegerField(default=0)),
                ('is_tax_exempt_default', models.BooleanField(default=False, help_text='Spec §9.12 — jurisdictions that zero-rate long leases. Leases inherit this at creation time via tax_exempt_override.')),
                ('is_archived', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_instalment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_seasons', to='seasons.instalmentplan')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='accounts.marina')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='berthlease',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='seasons.season'),
        ),
        migrations.CreateModel(
            name='SeasonalRateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('min_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('season_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('berth_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_cards', to='berths.berthcategory')),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='accounts.marina')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='seasons.season')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_cards', to='billing.taxrate')),
            ],
            options={
                'ordering': ['season', 'name'],
            },
        ),
        migrations.AddField(
            model_name='season',
            name='default_rate_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_seasons', to='seasons.seasonalratecard'),
        ),
        migrations.AddField(
            model_name='berthlease',
            name='rate_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='seasons.seasonalratecard'),
        ),
        migrations.CreateModel(
            name='LeaseInstalment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='scheduled', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_instalments', to='billing.invoice')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalments', to='seasons.berthlease')),
            ],
            options={
                'ordering': ['lease', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('lease', 'sequence'), name='lease_instalment_unique_sequence')],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('marina', 'name'), name='season_unique_name_per_marina'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='season_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='berthlease',
            index=models.Index(fields=['berth', 'start_date', 'end_date'], name='seasons_ber_berth_i_73caa3_idx'),
        ),
        migrations.AddIndex(
            model_name='berthlease',
            index=models.Index(fields=['member', 'status'], name='seasons_ber_member__8f54ce_idx'),
        ),
        migrations.AddIndex(
            model_name='berthlease',
            index=models.Index(fields=['status'], name='seasons_ber_status_c9a11d_idx'),
        ),
        migrations.AddConstraint(
            model_name='berthlease',
            constraint=models.UniqueConstraint(fields=('berth', 'season'), name='lease_unique_berth_per_season'),
        ),
        migrations.AddConstraint(
            model_name='berthlease',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='lease_start_before_end'),
        ),
    ]
