# Generated by Django 6.0.4 on 2026-04-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('vessel_type', models.CharField(choices=[('motor', 'Motor'), ('sail', 'Sail'), ('catamaran', 'Catamaran'), ('other', 'Other')], default='motor', max_length=20)),
                ('make', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('loa', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_offer', 'Under Offer'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('listed_at', models.DateField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.marina')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('viewing_scheduled', 'Viewing Scheduled'), ('viewing_completed', 'Viewing Completed'), ('offer_made', 'Offer Made'), ('sale_agreed', 'Sale Agreed')], default='new', max_length=30)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('walk_in', 'Walk-in'), ('broker', 'Broker'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.marina')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.listing')),
            ],
        ),
    ]
