# Generated by Django 6.0.4 on 2026-04-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reg', models.CharField(blank=True, max_length=100)),
                ('flag', models.CharField(blank=True, max_length=100)),
                ('mmsi', models.CharField(blank=True, max_length=20)),
                ('call_sign', models.CharField(blank=True, max_length=20)),
                ('vessel_type', models.CharField(choices=[('motor', 'Motor'), ('sail', 'Sail'), ('catamaran', 'Catamaran'), ('superyacht', 'Superyacht'), ('commercial', 'Commercial'), ('other', 'Other')], default='motor', max_length=20)),
                ('loa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('beam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('draft', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('air_draft', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('builder', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('engine', models.CharField(blank=True, max_length=200)),
                ('fuel', models.CharField(blank=True, max_length=50)),
                ('tank_cap', models.IntegerField(blank=True, help_text='Litres', null=True)),
                ('fw_tank', models.IntegerField(blank=True, help_text='Litres', null=True)),
                ('shore_power', models.CharField(blank=True, max_length=50)),
                ('mooring_pref', models.CharField(blank=True, max_length=100)),
                ('ais_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to='accounts.marina')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vessels', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flares_exp', models.DateField(blank=True, null=True)),
                ('life_raft_exp', models.DateField(blank=True, null=True)),
                ('epirb_exp', models.DateField(blank=True, null=True)),
                ('extinguisher_exp', models.DateField(blank=True, null=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_equipment', to='accounts.marina')),
                ('vessel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety', to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer', models.CharField(blank=True, max_length=200)),
                ('policy_no', models.CharField(blank=True, max_length=100)),
                ('expires', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('due_soon', 'Due Soon'), ('expired', 'Expired')], default='valid', max_length=20)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records', to='accounts.marina')),
                ('vessel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='vessels.vessel')),
            ],
        ),
    ]
