# Generated by Django 4.2.29 on 2026-04-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('registration', 'Registration Certificate'), ('ssr', 'Small Ships Register (SSR)'), ('part1', 'Part 1 Registry'), ('commercial', 'Commercial Certificate'), ('competence', 'Competence Certificate'), ('vhf', 'VHF / SRC Licence'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('issued', models.DateField(blank=True, null=True)),
                ('expires', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('due_soon', 'Due Soon'), ('expired', 'Expired'), ('missing', 'Missing')], default='valid', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('marina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessel_certificates', to='accounts.marina')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='vessels.vessel')),
            ],
        ),
    ]
