# Generated by Django 4.2.29 on 2026-04-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_vesselcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesselcertificate',
            name='cert_type',
            field=models.CharField(choices=[('registration', 'Registration Certificate'), ('ssr', 'Small Ships Register (SSR)'), ('part1', 'Part 1 Registry'), ('commercial', 'Commercial Certificate'), ('competence', 'Competence Certificate'), ('vhf', 'VHF / SRC Licence'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
