# Generated by Django 4.2.29 on 2026-04-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0003_cert_type_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vessel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vesselcertificate',
            options={'ordering': ['id']},
        ),
    ]
